baseurl = "https://sickyoon.github.io/"
title = "Sick Yoon"
languageCode = "en-us"
theme = "gobooks-theme"

[params]
  avatar = "https://avatars0.githubusercontent.com/u/24367477"
  description = "gopher & python enthusiast"
  copyright = "Sick Yoon"

