baseurl = "/"
title = "Sick Yoon"
metaDataFormat = "toml"
theme = "hugosy"
languageCode = "en_us"
description = "gopher & <br> software engineer"
copyright = "(c) 2016 Sick Yoon."

[author]
  name = "Sick Yoon"
  email = "sick.yoon@gmail.com"

[params]
  sidebartitle = "Sick Yoon"
  sidebartagline = "gopher & software engineer"
  sidebarphoto = "https://avatars0.githubusercontent.com/u/24367477?v=3&s=460"

[[menu.main]]
  name = "about"
  identifier = "about"
  pre = "<i class='fa fa-fw fa-info'></i>"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "projects"
  identifier = "projects"
  url = "/projects/"
  weight = 2

[[menu.main]]
  name = "resources"
  identifier = "resources"
  url = "/resources/"
  weight = 3

