baseurl = "sickyoon.com/"
title = "sickyoon.com"
copyright = "(c) 2016 Sick Yoon."
languageCode = "en-us"
metaDataFormat = "toml"
theme = "hyde-s"
paginate = 10
paginatePath = "page"

[author]
  name = "Sick Yoon"
  email = "sick.yoon@gmail.com"

[params]
  brand = "sickyoon.com"
  topline = "gopher & python enthusiast"
  sidebar = "left"
  home = "Posts"
  highlight = "default"
  github = "sickyoon"
  linkedin = ""
  rss = true

[blackfriday]
  angledQuotes = true
  fractions = false
  hrefTargetBlank = true
  latexDashes = true
  plainIdAnchors = true
  extensions = []
  extensionmask = []


